### ISSUE TITLE
Add Rest API feature

### ISSUE THREAD

**Issue by dachafra** [morph-csv/CSVW2RMLC#31]
Send and retrieve the results without the necessity to fill the UI form. Only send and retrieve the data via URL

**Comment by fpriyatna** [comment]
use this command: http://csvw2rmlc.mappingtranslator.mappingpedia.linkeddata.es/csvw2rmlc?csvw_url=https://raw.githubusercontent.com/morph-csv/CSVW2RMLC/master/examples/example7/csv-metadata.json

**Comment by dachafra** [comment]
Error: BadRequestKeyError: 400 Bad Request: KeyError: 'csvw_url'

**Comment by fpriyatna** [comment]
sorry, it's POST, not GET:
curl -X POST \
  'http://csvw2rmlc.mappingtranslator.mappingpedia.linkeddata.es/csvw2rmlc?csvw_url=https://raw.githubusercontent.com/morph-csv/CSVW2RMLC/master/examples/example7/csv-metadata.json' \
  -H 'Postman-Token: b78da32f-3611-4d1b-a7bb-f0fc4b68b7e4' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F csvw_url=https://raw.githubusercontent.com/morph-csv/CSVW2RMLC/master/examples/example7/csv-metadata.json

**Comment by fpriyatna** [comment]
both GET and POST now work

**Comment by fpriyatna** [comment]
done
